name: Create zip archive on tag

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: montudor/action-zip@v1.0.0
      
      - name: Create zip archive
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          echo ${BRANCH_NAME}
          zip -r temp.zip .
          echo HERE 1
          mkdir temp_folder
          mv temp.zip temp_folder
          cd temp_folder
          unzip temp.zip
          echo HERE 2
          mv shopware-5-${BRANCH_NAME} IvyPaymentPlugin
          echo HERE 3
          zip -r IvyPaymentPlugin-${BRANCH_NAME}.zip IvyPaymentPlugin

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          files: /temp_folder/IvyPaymentPlugin-${BRANCH_NAME}.zip