name: Create zip archive on tag

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: montudor/action-zip@v1.0.0
      
      - name: Create zip archive
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          zip -r temp.zip .
          echo HERE 1
          mkdir IvyPaymentPlugin
          ls
          unzip temp.zip -d IvyPaymentPlugin
          ls
          echo HERE 3
          zip -r IvySW5-${BRANCH_NAME}.zip IvyPaymentPlugin
          ls

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: IvySW5-${BRANCH_NAME}.zip
          path: IvySW5-${BRANCH_NAME}.zip